name: Testing SFTP

on: 
  push:
    branches:
      [ master ]

jobs:
  # stage_sftp:
  #   name: Initializing SFTP
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Get latest code
  #     uses: actions/checkout@v3
  #   - name: Creating Keys
  #     run: |
  #       mkdir keys && cd keys
  #       touch ssh_host_rsa_key.pub
  #       echo "${{ secrets.RSA_PUB }}" >> ssh_host_rsa_key.pub
  #       touch ssh_host_ed25519_key.pub
  #       echo "${{ secrets.ED25519_PUB }}" >> ssh_host_ed25519_key.pub
  #       ls
  #   - name: Creating Config ENV
  #     run: |
  #       touch .env
  #       echo "${{ secrets.SFTP_CONFIG_ENV }}" >> .env
  #   - name: Docker Login
  #     env: 
  #       DOCKER_USER: ${{ secrets.DOCKER_USER }}
  #       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #     run:
  #       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  #   - name: Building Image and Pushing to DockerHub
  #     run: |
  #       docker-compose build
  #       docker compose push

  # sftp_on_server:
  #   # needs: stage_sftp
  #   name: Initializing SFTP
  #   runs-on: ubuntu-latest
  #   steps: 
  #   - name: Initializing SFTP Container
  #     uses: appleboy/ssh-action@master
  #     env:
  #       RSA_PUB: "${{ secrets.RSA_PUB }}"
  #       ED25519_PUB: "${{ secrets.ED25519_PUB }}"
  #       SFTP_CONF_ENV: "${{ secrets.SFTP_CONFIG_ENV }}"
  #       COMPOSE: "${{ secrets.COMPOSE }}"
  #       SCRIPT: "${{ secrets.SCRIPT }}"
  #     with:
  #       host: ${{ secrets.SERVER }}
  #       username: ${{ secrets.SSH_USERNAME }}
  #       key: ${{ secrets.SSH_KEY }}
  #       port: ${{ secrets.SSH_PORT }}
  #       passphrase: ${{ secrets.SSH_PASSPHRASE }}
  #       envs: RSA_PUB, ED25519_PUB, SFTP_CONF_ENV, COMPOSE, SCRIPT
  #       script: |
  #         cd /home/
  #         touch script.sh
  #         echo "$SCRIPT" >> script.sh
  #         chmod +x script.sh
  #         ./script.sh

  transferring_files:
    name: Transferring files
    runs-on: ubuntu-latest
    # needs: sftp_on_server 
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    # - name: Configuring LFTP
    #   run: |
    #     sudo apt-get update
    #     # sudo apt install lftp
    - name: Running Script 
      run: |
        ls -l
        echo "Updating perms of build"
        chmod 665 build
        echo "Updated"
        ls -l
        chmod +x script.sh 
        ./script.sh
