name: Dockerized SFTP

on: 
  push:
    branches:
      [ master ]

env:
  sftp_host: ${{ secrets.SFTP_HOST }}
  sftp_user: ${{ secrets.SFTP_USER }}
  sftp_password: ${{ secrets.SFTP_PASSWORD }}

jobs:
  transferring_files:
    name: Transferring files
    runs-on: ubuntu-latest
    steps:
      # Getting Latest code
    - name: Get latest code
      uses: actions/checkout@v3
      
      # Installing LFTP on our GitHub Hosted Runner
    - name: Configuring LFTP
      run: |
        sudo apt-get update
        sudo apt update
        sudo apt install lftp

      # Running script.sh
    - name: Running Script 
      run: |
        chmod 765 build                 
        echo "Updated Perms of Build"
        echo "-----------------------------------------------------------------------------------------------------------------"
        echo "Executing script:"
        chmod +x script.sh 
        ./script.sh
      # We also boost the perms of the build folder, 
      # the sample folder that has the contents we need to transfer.